connection_info:
  user: CI_STATS_DB_USER
  pass: CI_STATS_DB_PASS
  host: CI_STATS_DB_HOST
  database: CI_STATS_DB_NAME
  port: PG_PORT
tables:
  spec_profiling_results:
    import_db: CI_STATS_DB
    import_query: >
      SELECT id
      FROM spec_profiling_results
    export_schema: 'ci_stats'
    export_table: 'spec_profiling_results'
    export_table_primary_key: id
