connection_info:
  database: GITLAB_PROFILER_DB_NAME
  host: GITLAB_PROFILER_DB_HOST
  pass: GITLAB_PROFILER_DB_PASS
  port: PG_PORT
  user: GITLAB_PROFILER_DB_USER
tables:
  request_stats:
    export_db: EXPORT_DB
    export_schema: 'gitlab_profiler'
    export_table: 'request_stats'
    export_table_primary_key: id
    import_db: GITLAB_PROFILER_DB
    import_query: |-
      SELECT id
      , url
      , auth_type
      , html_url
      , sql_url
      , gitlab_version
      , status_code
      , view_time_ms
      , sql_time_ms
      , total_ms
      , created_at
      , started_at
      , ended_at
      FROM request_stats
