version: 2

models:
  - name: zuora_accounts_new_updated
    columns:
      - name: date_day
        tests:
          - not_null
  - name: zuora_subscriptions_new_updated
    columns:
      - name: date_day
        tests:
          - not_null

