version: 2

models:
    - name: monthly_usage_data_28_days
      description: '{{ doc("monthly_usage_data_28_days") }}'
      tests:
      - unique:
          column_name: "concat(host_id, instance_id, created_month, metrics_path)"
      columns:
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: clean_metrics_name
            tests:
              - not_null
    - name: monthly_usage_data_all_time
      description: '{{ doc("monthly_usage_data_all_time") }}'
      columns:
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: clean_metrics_name
            tests:
              - not_null
    - name: usage_data_28_days_flattened
      description: '{{ doc("usage_data_28_days_flattened") }}'
      columns:
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: clean_metrics_name
            tests:
              - not_null
    - name: usage_data_all_time_flattened
      description: '{{ doc("usage_data_all_time_flattened") }}'
      columns:
          - name: ping_id
            tests:
              - not_null
          - name: instance_id
            tests:
              - not_null
          - name: clean_metrics_name
            tests:
              - not_null
