version: 2

models:
  - name: bamboohr_compensation
    description: A log of compensation and compensation related updates. We don't pull in the most sensitive compensation-related data, such as salary.
    columns:
      - name: compensation_update_id
        tests:
            - unique
            - not_null