version: 2

models:
  - name: bamboohr_compensation
    description: A log of compensation and compensation related updates. This model is temporary and is used for downstream models.
    columns:
      - name: compensation_update_id
        tests:
            - unique
            - not_null
      - name: employee_id
        description: Foreign Key to employee info
        tests:
            - not_null
      - name: effective_date
        description: Date the compensation change goes into effect
        tests:
          - not_null
      - name: compensation_type
      - name: compensation_change_reason
        description: Compensation can change because of promotions, role changes, annual reviews and for other reasons.
        tests:
          - not_null
      - name: pay_rate
      - name: compensation_value
        tests:
          - not_null
      - name: compensation_currency
      - name: uploaded_at    

  - name: bamboohr_currency_conversion
    description: This table tells us what the conversion is for local salary to USD.
    columns:
      - name: conversion_id
        tests:
          - unique
          - not_null
      - name: employee_id 
        description: Foreign Key to employee info
        tests:
          - not_null
      - name: effective_date
      - name: currency_conversion_factor
      - name: local_annual_salary_amount
      - name: local_currency_code
      - name: usd_annual_salary_amount
      - name: prior_bamboohr_annual_salary     

  - name: bamboohr_custom_bonus
    description: There are multiple bonuses that a team member can earn that are captured here.
    columns:
      - name: bonus_id
        tests:
            - unique
            - not_null
      - name: employee_id
        description: Foreign Key to employee info
        tests:
            - not_null
      - name: bonus_type
        tests:
          - not_null
      - name: bonus_date
        tests:
          - not_null
  - name: bamboohr_directory
    description: Base model for BambooHR Active Directory. This only shows currently active employees.
    columns:
      - name: employee_id
        tests:
            - unique
            - not_null
      - name: full_name
        tests:
            - unique
            - not_null
      - name: job_title
  
  - name: bamboohr_emergency_contacts
    description: Bamboohr emergency contacts table. Used to create an alert in bamboohr_missing_emergency_contact_alert to identify individuals we do not have a contact for.
    columns:
      - name: employee_id
      - name: full_name
      - name: home_phone
      - name: mobile_phone
      - name: work_phone

  - name: bamboohr_employment_status
    description: This model shows changes in employment status (active, terminated, on leave, etc). Updates are captured in log-style.
    columns:
      - name: status_id
        tests:
            - unique
            - not_null
      - name: employee_id
        tests:
            - not_null
            
  - name: bamboohr_id_employee_number_mapping
    description: This model is the canonical source mapping bamboo employee numbers with employee IDs. It includes all employees for all time. The model also captures demographic information, and removes test accounts.
    columns:
      - name: greenhouse_candidate_id
        description: Captures the id associated to the employee in Greenhouse (our recruiting platform). This will only be applicable in Greenhouse starting 2019-12-13, and will help identify which candidates were hired.
        tests: 
            - unique          
  - name: bamboohr_job_info
    description: This model shows the details (manager, department, and division) that an employee is in at a given point in time. This includes historical information.
    columns:
      - name: job_id
        tests:
            - unique
            - not_null
      - name: employee_id
        tests:
            - not_null
      - name: job_title
        tests:
            - not_null
      - name: effective_date
        tests:
            - not_null
      - name: department
      - name: division
      - name: entity
        tests:
            - not_null
      - name: reports_to
        tests:
            - not_null
      - name: job_role      
  - name: bamboohr_job_role
    description: This model shows the job role an employee is in and when their role changes. The data for this table comes from bamboohr_id_emmployee_number_mapping raw. We started capturing data points not in other reports starting 2020.02.27
    columns:
      - name: employee_number
        tests:
            - not_null
      - name: employee_id
        tests:
            - not_null
      - name: job_role
      - name: job_grade
      - name: cost_center
      - name: jobtitle_speciality
        description: Started capturing on 2020.05.07
      - name: gitlab_username       
      - name: pay_frequency
        description: The number of compensation periods. Started capturing on 2020.09.10
      - name: sales_geo_differential
      - name: pay_frequency
      - name: effective_date
        description: The date the role is effective until a change occurs. 
  - name: bamboohr_locality
    description: This shows the locality for employees starting 2020.03.24 (the 1st date we started capturing from bamboohr) on a daily basis.
    columns: 
        - name: employee_number
        - name: employee_id
        - name: first_name
        - name: last_name
        - name: hire_date
        - name: locality
        - name: updated_at

  - name: bamboohr_ote
    description: Provides on-target-earning as related to sales roles.
    columns:
      - name: target_earnings_update_id
        tests:
          - unique
          - not_null
      - name: employee_id
        description: Foreign Key to employee info
        tests:
          - not_null
      - name: effective_date
      - name: variable_pay
      - name: annual_amount_local
      - name: annual_amount_usd_value
      - name: ote_local
      - name: ote_usd
      - name: ote_type
 