{%- macro map_product_category(rate_plan_name) -%}
   CASE
   WHEN LOWER( {{rate_plan_name}} ) LIKE '%gold%'
    THEN 'SaaS - Ultimate'
  WHEN LOWER( {{rate_plan_name}} )  LIKE '%silver%'
    THEN 'SaaS - Premium'
  WHEN LOWER( {{rate_plan_name}} ) LIKE '%ultimate%'
    THEN 'Self-Managed - Ultimate'
  WHEN LOWER( {{rate_plan_name}} ) LIKE '%premium%'
    THEN 'Self-Managed - Premium'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'bronze%'
    THEN 'SaaS - Bronze'
  WHEN LOWER( {{rate_plan_name}} ) LIKE '%starter%'
    THEN 'Self-Managed - Starter'
  WHEN LOWER( {{rate_plan_name}} )  LIKE 'gitlab enterprise edition%'
    THEN 'Self-Managed - Starter'
  WHEN {{rate_plan_name}} = 'Pivotal Cloud Foundry Tile for GitLab EE'
    THEN 'Self-Managed - Starter'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'plus%'
    THEN 'Plus'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'standard%'
    THEN 'Standard'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'basic%'
    THEN 'Basic'
  WHEN {{rate_plan_name}} = 'Trueup'
    THEN 'Trueup'
  WHEN LTRIM(LOWER( {{rate_plan_name}} )) LIKE 'githost%'
    THEN 'GitHost'
  WHEN LOWER( {{rate_plan_name}} ) LIKE '%quick start with ha%'
    THEN 'Support'
  WHEN TRIM( {{rate_plan_name}} ) IN (
                                      'GitLab Service Package'
                                    , 'Implementation Services Quick Start'
                                    , 'Implementation Support'
                                    , 'Support Package'
                                    , 'Admin Training'
                                    , 'CI/CD Training'
                                    , 'GitLab Project Management Training'
                                    , 'GitLab with Git Basics Training'
                                    , 'Travel Expenses'
                                    , 'Training Workshop'
                                    , 'GitLab for Project Managers Training - Remote'
                                    , 'GitLab with Git Basics Training - Remote'
                                    , 'GitLab for System Administrators Training - Remote'
                                    , 'GitLab CI/CD Training - Remote'
                                    , 'InnerSourcing Training - Remote for your team'
                                    , 'GitLab DevOps Fundamentals Training'
                                    , 'Self-Managed Rapid Results Consulting'
                                    , 'Gitlab.com Rapid Results Consulting'
                                    )
    THEN 'Support'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'gitlab geo%'
    THEN 'Other'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'ci runner%'
    THEN 'Other'
  WHEN LOWER( {{rate_plan_name}} ) LIKE 'discount%'
    THEN 'Other'
  WHEN TRIM( {{rate_plan_name}} ) IN (
                                      '#movingtogitlab'
                                    , 'File Locking'
                                    , 'Payment Gateway Test'
                                    , 'Time Tracking'
                                    , '1,000 CI Minutes'
                                    , 'Gitlab Storage 10GB'
                                    )
    THEN 'Other'
  ELSE 'Not Applicable'
  END
{% endmacro %}
