version: 2

models:

    - name: dbt_run_results_source
      description: "Information about compilation/execution time for DBT models."
      columns:
        - name: compilation_completed_at
        - name: compilation_started_at
        - name: model_execution_time
        - name: model_name

    - name: dbt_snapshots_results_source
      description: Run results for dbt snapshot

    - name: dbt_source_freshness_results_source
      description: "Monitoring information about DBT sources"
      columns:
        - name: freshness_observed_at
          tests:
            - not_null
        - name: latest_load_at
          tests:
            - not_null
        - name: source_freshness_state
          tests:
            - not_null
        - name: table_name
          tests:
            - not_null
        - name: time_since_loaded_seconds
          tests:
            - not_null

    - name: dbt_source_test_results_source
      description: Run results for dbt test specifically on sources.

    - name: dbt_test_results_source
      description: "DBT test results by name and time"
      columns:
        - name: is_failed_test
          tests:
            - not_null
        - name: is_warned_test
          tests:
            - not_null
        - name: test_error
        - name: test_execution_time_elapsed
          tests:
            - not_null
        - name: test_name
          tests:
            - not_null
        - name: test_result_generated_at
          tests:
            - not_null
        