version: 2

models:
  - name: mart_arr
    description: '{{ doc("mart_arr") }}'
    columns:
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: primary_key
        tests:
            - not_null
            - unique
      - name: is_reseller
        description: Identify whether a crm_account is a reseller.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.

  - name: mart_arr_snapshots
    description: Daily snapshots of MRR/ARR by month values per customer, subscription and product
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: mart_discount_arr
    description: Model with Invoiced ARR used to calculate discounts across various dimensions.
    columns:
      - name: invoice_item_month_id
        description: Unique identifier of the transaction on the invoice amortized by month.
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "arr"]
        
  - name: mart_delta_arr_parent_month
    description: "Mart table by month pursuant to the ARR Analysis Framework at the parent customer level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: mart_delta_arr_subscription_month
    description: "Mart table by month purusant to the ARR Analysis Framework at the subscription level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: mart_retention_parent_account
    description: "Mart table to support drillable retention analysis"

  - name: usage_ping_mart
    description: '{{ doc("usage_ping_mart") }}'
    columns:
      - name: usage_ping_id
        tests:
          - not_null
          - unique
      - name: uuid
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null
