version: 2

models:
  - name: mart_arr
    description: '{{ doc("mart_arr") }}'
    columns:
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: primary_key
        tests:
            - not_null
            - unique
      - name: is_reseller
        description: Identify whether a crm_account is a reseller.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.
  - name: mart_arr_incr
    description: '{{ doc("mart_arr_incr") }}'
    columns:
      - name: primary_key
        tests:
          - not_null
  - name: mart_delta_arr_parent_month
    description: "Mart table by month purusant to the ARR Analysis Framework at the parent customer level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags:
          - tdf
          - mart
          - arr
  - name: mart_delta_arr_parent_quarter
    description: "Mart table by quarter purusant to the ARR Analysis Framework at the parent customer level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags:
          - tdf
          - mart
          - arr
  - name: mart_delta_arr_parent_year
    description: "Mart table by year purusant to the ARR Analysis Framework at the parent customer level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags:
          - tdf
          - mart
          - arr
  - name: mart_delta_arr_subscription_month
    description: "Mart table by month purusant to the ARR Analysis Framework at the subscription level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags:
          - tdf
          - mart
          - arr
  - name: usage_ping_mart
    description: '{{ doc("usage_ping_mart") }}'
    columns:
      - name: usage_ping_id
        tests:
          - not_null
          - unique
      - name: uuid
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null
