version: 2

models:
  - name: license_db_add_ons_source
    description: '{{ doc("license_db_add_ons_source") }}'
    columns:
      - name: add_on_id
        tags:
          - tdf
          - license_db
        tests:
          - not_null
          - unique

  - name: license_db_granted_add_ons_source
    description: '{{ doc("license_db_granted_add_ons_source") }}'
    columns:
      - name: granted_add_on_id
        tags:
          - tdf
          - license_db
        tests:
          - not_null
          - unique
      - name: license_id
        tags:
          - tdf
          - license_db
        tests:
          - not_null
      - name: add_on_id
        tags:
          - tdf
          - license_db
        tests:
          - not_null
          - relationships:
              to: ref('license_db_add_ons_source')
              field: add_on_id

  - name: license_db_licenses_source
    description: '{{ doc("license_db_licenses_source") }}'
    columns:
      - name: license_id
        tags:
          - tdf
          - license_db
        tests:
          - not_null
          - unique
      - name: created_at
        tags:
          - tdf
          - license_db
        tests:
          - not_null
      - name: updated_at
        tags:
          - tdf
          - license_db
        tests:
          - not_null
      - name: email
        meta:
          sensitive: true            
