version: 2

models:
  - name: prep_sfdc_account
    description: '{{ doc("prep_sfdc_account") }}'
    columns:
      - name: crm_account_id
        description: CRM Account ID provided by Salesforce
        tests:
          - not_null
      - name: tsp_sub_region_clean
        description: Sales sub region, temp cleaning column
      - name: tsp_region_clean
        description: Sales region, temp cleaning column
      - name: tsp_area_clean
        description: Sales area, temp cleaning column
      - name: tsp_territory_clean
        description: Sales territory, temp cleaning column
      - name: df_industry_clean
        description: Industry, temp cleaning column
      - name: ultimate_parent_sales_segment_clean
        description: Ultimate parent sales segment, temp cleaning column
      - name: dim_geo_area_name_source
        description: Dim geo area name final source column
      - name: dim_geo_region_name_source
        description: Dim geo region name final source column
      - name: dim_geo_sub_region_name_source
        description: Dim geo sub region name final source column
      - name: dim_sales_territory_name_source
        description: Dim sales territory name final source column
      - name: dim_industry_name_source
        description: Dim industry name final source column
      - name: dim_sales_segment_name_source
        description: Dim sales segment name final source column

  - name: prep_crm_sales_hierarchy_live
    description: '{{ doc("prep_crm_sales_hierarchy_live") }}'
    columns:
      - name: dim_crm_sales_hierarchy_live_id
        description: Unique identifier of a sales hierarchy tier
        tests:
          - not_null
          - unique

  - name: prep_crm_sales_representative
    description: '{{ doc("prep_crm_sales_representative") }}'
    columns:
      - name: dim_crm_sales_rep_id
        description: Unique identifier of a sales representative
        tests:
          - not_null
          - unique

  - name: prep_crm_sales_hierarchy_stamped
    description: '{{ doc("prep_crm_sales_hierarchy_stamped") }}'
    columns:
      - name: dim_crm_sales_hierarchy_stamped_id
        description: Unique identifier of a sales hierarchy tier
        tests:
          - not_null
          - unique

  - name: prep_geo_area
    description: '{{ doc("prep_geo_area") }}'
    columns:
      - name: dim_geo_area_id
        description: Unique identifier of a geo area
        tests:
          - not_null
          - unique

  - name: prep_geo_region
    description: '{{ doc("prep_geo_region") }}'
    columns:
      - name: dim_geo_region_id
        description: Unique identifier of a geo region
        tests:
          - not_null
          - unique

  - name: prep_geo_sub_region
    description: '{{ doc("prep_geo_sub_region") }}'
    columns:
      - name: dim_geo_sub_region_id
        description: Unique identifier of a geo sub region
        tests:
          - not_null
          - unique

  - name: prep_industry
    description: '{{ doc("prep_industry") }}'
    columns:
      - name: dim_industry_id
        description: Unique identifier of an industry
        tests:
          - not_null
          - unique

  - name: prep_location_region
    description: '{{ doc("prep_location_region") }}'
    columns:
      - name: dim_location_region_id
        description: Unique identifier of a geographical region
        tests:
          - not_null
          - unique

  - name: prep_marketing_channel
    description: '{{ doc("prep_marketing_channel") }}'
    columns:
      - name: dim_marketing_channel_id
        description: Unique identifier of a marketing channel
        tests:
          - not_null
          - unique

  - name: prep_namespace
    description: '{{ doc("dim_namespace") }}'
    columns:
      - name: dim_namespace_id
        tests:
          - not_null
          - unique
      - name: namespace_id
        tests:
          - not_null
          - unique
      - name: namespace_is_internal
      - name: namespace_is_ultimate_parent
      - name: namespace_name
      - name: namespace_path
      - name: owner_id
      - name: namespace_type
        description: This field should be Group or Individual. A namespace is the first item to come after the / following the domain. For example https://www.gitlab.com/NicoleSchwartz/ is an Individual namespace. There are some namespace_IDs that are missing from this table, when doing certain joins (left) you may get NULL when this data is missing.
        tests:
          - not_null
      - name: has_avatar
      - name: namespace_created_at
      - name: namespace_updated_at
      - name: is_membership_locked
      - name: has_request_access_enabled
      - name: has_share_with_group_locked
      - name: visibility_level
      - name: dap_sync_status
      - name: ldap_sync_error
      - name: ldap_sync_last_update_at
      - name: ldap_sync_last_successful_update_at
      - name: ldap_sync_last_sync_at
      - name: lfs_enabled
      - name: parent_id
      - name: shared_runners_minutes_limit
      - name: extra_shared_runners_minutes_limit
      - name: repository_size_limit
      - name: does_require_two_factor_authentication
      - name: two_factor_grace_period
      - name: project_creation_level
      - name: push_rule_id
      - name: creator_id
      - name: ultimate_parent_namespace_id
      - name: gitlab_plan_id
        description: The **plan_id** associated with the namespace's subscription. This can be inherited from the namespace's ultimate parent.
        tests:
          - not_null
          - accepted_values:
              values: ['2', '3', '4', '34', '67', 'Trial']
      - name: gitlab_plan_title
        description: Whether or not the namespace associated with the project is subscribed to a paid plan. This can be inherited from the namespace's ultimate parent.
        tests:
          - not_null
      - name: gitlab_plan_is_paid
        description: Whether or not the namespace associated with the project is subscribed to a paid plan. This can be inherited from the namespace's ultimate parent.
        tests:
          - not_null
      - name: dim_product_tier_id,
      - name: current_member_count
        description: The number of members that are presently associated with the namespace.
      - name: current_project_count
        description: The number of projects that are presently associated with the namespace.

  - name: prep_opportunity_source
    description: '{{ doc("prep_opportunity_source") }}'
    columns:
      - name: dim_opportunity_source_id
        description: Unique identifier of an opportunity source
        tests:
          - not_null
          - unique

  - name: prep_order_type
    description: '{{ doc("prep_order_type") }}'
    columns:
      - name: dim_order_type_id
        description: Unique identifier of an order type
        tests:
          - not_null
          - unique

  - name: prep_purchase_channel
    description: '{{ doc("prep_purchase_channel") }}'
    columns:
      - name: dim_purchase_channel_id
        description: Unique identifier of a purchase channel
        tests:
          - not_null
          - unique

  - name: prep_recurring_charge
    description: '{{ doc("prep_recurring_charge") }}'
    columns:
      - name: mrr_id
        description: The unique identifier of the MRR.
        tests:
          - not_null
          - unique
      - name: dim_date_id
        description: The identifier of date month in dim_date
      - name: dim_subscription_id
        description: The identifier of subscription in dim_subscriptions table
        tests:
          - not_null
      - name: dim_product_detail_id
        description: The identifier of product details in dim_product_detail
        tests:
          - not_null
      - name: dim_billing_account_id
        description: Zuora account id
      - name:  dim_crm_account_id
        description: account id frm crm
      - name: mrr
        description: Monthly Recurring Revenue value for given month
      - name: arr
        description: Annual Recurring Revenue value for given month
      - name: quantity
        description: Total quantity

  - name: prep_sales_segment
    description: '{{ doc("prep_sales_segment") }}'
    columns:
      - name: dim_sales_segment_id
        description: Unique identifier of a sales segment
        tests:
          - not_null
          - unique

  - name: prep_sales_territory
    description: '{{ doc("prep_sales_territory") }}'
    columns:
      - name: dim_sales_territory_id
        description: Unique identifier of a geo area
        tests:
          - not_null
          - unique

  - name: prep_subscription
    description: '{{ doc("prep_subscription") }}'
    columns:
      - name: dim_subscription_id
        description: Unique identifier of a version of a subscription
        tests:
          - not_null
          - unique
      - name: dim_crm_account_id
        description: account id from SFDC identifing the customer
      - name: dim_billing_account_id
        description: The id of the Zuora account the subscription is associated with
      - name: dim_crm_person_id_invoice_owner
      - name: dim_crm_opportunity_id
      - name: dim_subscription_id_original
      - name: dim_subscription_id_previous
      - name: amendment_id
      - name: subscription_name_slugify
        description: The unique identifier of the subscription
      - name: subscription_status
        description: The status of the subscription
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Cancelled', 'Draft', 'Expired']
      - name: subscription_version
        description: The version number of the subscription
      - name: is_auto_renew
        description: Boolean field, if true, this subscription automatically renews at the end of the subscription term
      - name: zuora_renewal_subscription_name
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: zuora_renewal_subscription_name_slugify
        description: name of the linked subscription that renews the prior subscription in a lineage
      - name: renewal_term
        description: The length of the period for the subscription renewal term
      - name: renewal_term_period_type
        description: The period type for the subscription renewal term. This field is used with the renewal term field to specify the subscription renewal term.
      - name: subscription_start_date
        description: The date when the subscription term starts. This date is the same as the start date of the original term, which isn't necessarily the start date of the current or new term.
      - name: subscription_end_date
        description: The date when the subscription term ends, where the subscription ends at midnight the day before. For example, if the SubscriptionEndDate is 12/31/2016, the subscriptions ends at midnight (00:00:00 hours) on 12/30/2016. This date is the same as the term end date or the cancelation date, as appropriate.
      - name: subscription_start_month
        description: The month when the subscription term starts. This month is the same as the start month of the original term, which isn't necessarily the start month of the current or new term.
      - name: subscription_end_month
        description: The month when the subscription term ends. This month is the same as the term end month or the cancelation month, as appropriate.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.
        tests:
          - not_null
          - accepted_values:
                  values: ['Sales-Assisted', 'Self-Service']

  - name: prep_subscription_lineage
    description:  '{{doc("prep_subscription_lineage")}}'
    columns:
        - name: subscription_name_slugify
          tests:
            - not_null
            - unique
        - name: lineage
          description: "All the subscriptions subsquent to the primary subscription, separated by commas."

  - name: prep_subscription_lineage_parentage_finish
    description: '{{ doc("prep_subscription_lineage_parentage_finish") }}'
    columns:
        - name: ultimate_parent_sub
          tests:
            - not_null
        - name: child_sub
          tests:
            - not_null
            - unique
        - name: cohort_month
          tests:
            - not_null
        - name: cohort_quarter
          tests:
            - not_null
        - name: cohort_year
          tests:
            - not_null
  - name: prep_subscription_lineage_parentage_start
    description: '{{doc("prep_subscription_lineage_parentage_start")}}'

  - name: prep_subscription_lineage_intermediate
    description: '{{ doc("prep_subscription_lineage_intermediate") }}'
    columns:
      - name: sub_row
        tests:
          - not_null
          - accepted_values:
              values: [ '1' ]
      - name: subscription_id
        tests:
          - not_null
          - unique
      - name: subscription_status
        tests:
          - not_null
          - accepted_values:
              values: [ 'Active','Cancelled' ]

  - name: prep_product_tier
    description: '{{ doc("prep_product_tier") }}'
    columns:
      - name: dim_product_tier_id
        description: "The unique identifier of Pricing tiers for Zuora Products"
        tests:
          - not_null
          - unique
      - name: product_tier_historical
        description: Product pricing tiers prior to [tier renaming](https://gitlab-com.gitlab.io/packaging-and-pricing/pricing-handbook/handbook/renaming_tiers/) (early 2021).
        tests:
          - not_null
          - unique
      - name: product_tier_historical_short
        description: Pulls the product tier from `product_tier_historical` with the delivery type removed
      - name: product_tier_name
        description: Product [pricing tiers](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/) for both SaaS and Self-Managed customers. Includes the mapping from SaaS - Silver to SaaS - Premium, and from SaaS - Gold to SaaS - Ultimate. 
        tests:
          - not_null
      - name: product_tier_name_short
        description: Pulls the product tier from `product_tier_name` with the delivery type removed
      - name: product_delivery_type
        description: "How product is delivered to customer; SaaS or Self-Managed (or Other)"
      - name: product_ranking
        description: "Numeric product pricing tier, independent of delivery type"

  - name: prep_quote
    description: '{{ doc("prep_quote") }}'
    columns:
      - name: dim_quote_id
        description: The unique identifier for each of the quotes.
        tests:
          - not_null
          - unique
      - name: quote_number
      - name: quote_name
      - name: quote_status
      - name: is_primary_quote
      - name: quote_start_date

  - name: prep_license
    description: '{{ doc("prep_license") }}'
    columns:
      - name: dim_license_id
        description: The unique ID of a generated license.
        tests:
          - not_null
          - unique
      - name: license_md5
        description: The md5 hash of the license file. Use this field to join to fct_usage_ping_payloads.
        tests:
          - not_null
          - unique
      - name: dim_subscription_id
        description: The unique identifier of a version of a subscription.
      - name: subscription_name
        description: The unique identifier of a subscription.
      - name: dim_subscription_id_original
      - name: dim_subscription_id_previous
      - name: license_user_count
        description: The user count of the license.
      - name: license_plan
        description: The plan code for the product tier of the license.
      - name: dim_product_tier_id
        description: The unique ID of a product tier deterimined in dim_product_tier.
      - name: is_trial
        description: Boolean flag noting if the license was generated as part of a trial.
      - name: is_internal
        description: Derived boolean flag noting if the email recipient and company associated with the license is part of GitLab.
      - name: company
        description: The company the license was generated for.
      - name: license_start_date
        description: The start date of the license.
      - name: license_expire_date
        description: The expiration date of the license.
      - name: created_at
        description: The timestamp of when the license was generated.
      - name: updated_at
        description: The timestamp of when the license was updated.

  - name: prep_usage_self_managed_seat_link
    description: '{{ doc("prep_usage_self_managed_seat_link") }}'
    columns:
      - name: customers_db_order_id
        tests:
          - not_null
      - name: order_subscription_id
        description: Zuora subscription ID listed on the order in the Customers source database.
      - name: dim_subscription_id
        tests:
          - not_null
      - name: dim_subscription_id_original
        tests:
          - not_null
      - name: dim_subscription_id_previous
        tests:
          - not_null
      - name: dim_crm_account_id
        tests:
          - not_null
      - name: dim_billing_account_id
        tests:
          - not_null
      - name: dim_product_tier_id
        tests:
          - not_null
      - name: active_user_count
        description: Count of active users currently on the customer's subcription. A count of 0 indicates that Seat Link has been turned off by the customer.
      - name: license_user_count
        description: Count of licensed users purchased with the customer's subcription.
        tests:
          - not_null
      - name: max_historical_user_count
        description: Maximum active user count ever reported over the lifetime of the customer's subcription.
        tests:
          - not_null
      - name: report_date
        description: Day on which Seat Link usage data is reported. Should always be last day of month for historical months.
        tests:
          - not_null
      - name: is_last_seat_link_report_per_subscription
        description: Flags if the row contains the most recent seat link record received for the subscription.
      - name: is_last_seat_link_report_per_order
        description: Flags if the row contains the most recent seat link record received for the order.
      - name: is_subscription_data_quality_issue
        description: Flags rows where the `zuora_subscription_id` from `customers_db_orders_source` is not found in `dim_subscription`.
      - name: is_rate_plan_data_quality_issue
        description: Flags rows where the `product_rate_plan_id` from `customers_db_orders_source` is not found in `dim_product_tier`.
      - name: is_active_user_count_data_quality_issue
        description: Flags rows where `active_user_count` is NULL in source.
